import { Pharmacy, DemoLocation } from '../../types/pharmacy';
import { normalizeMedicineName } from '../../utils/medicineNormalization';
import { PharmacyDataProvider } from './pharmacyProvider';

export const DEMO_USER_LOCATION: DemoLocation = {
  latitude: 12.9716,
  longitude: 77.5946,
  address: '102, Palm Grove Heights, 12th Main Road, Indiranagar, Bengaluru',
};

/**
 * Large network of demo pharmacies with comprehensive Indian medicine inventory.
 * Covers the most commonly prescribed medicines in India so real prescriptions work.
 */
export const DEMO_PHARMACIES_DATA: Pharmacy[] = [
  {
    id: "pharm_citycare",
    name: "CityCare Pharmacy",
    address: "100ft Road, Indiranagar",
    latitude: 12.9782,
    longitude: 77.6408,
    open: true,
    preparationTimeMinutes: 4,
    deliveryTimeMinutes: 7,
    rating: 4.8,
    phone: "+91 80 4123 4567",
    tagline: "High-speed dispensing hub with express courier dispatch",
    inventory: [
      { medicineName: "Dolo 650",              normalizedMedicineName: normalizeMedicineName("Dolo 650"),              availableQuantity: 100, unit: "strip",   unitPrice: 32  },
      { medicineName: "Pantoprazole",           normalizedMedicineName: normalizeMedicineName("Pantoprazole"),          availableQuantity: 60,  unit: "strip",   unitPrice: 75  },
      { medicineName: "Azithromycin",           normalizedMedicineName: normalizeMedicineName("Azithromycin"),          availableQuantity: 40,  unit: "strip",   unitPrice: 120 },
      { medicineName: "ORS",                    normalizedMedicineName: normalizeMedicineName("ORS"),                   availableQuantity: 50,  unit: "sachet",  unitPrice: 22  },
      { medicineName: "Paracetamol 500mg",      normalizedMedicineName: normalizeMedicineName("Paracetamol 500mg"),     availableQuantity: 150, unit: "strip",   unitPrice: 20  },
      { medicineName: "Amoxicillin",            normalizedMedicineName: normalizeMedicineName("Amoxicillin"),           availableQuantity: 50,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Augmentin 625mg",        normalizedMedicineName: normalizeMedicineName("Augmentin 625mg"),       availableQuantity: 45,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Augmentin",              normalizedMedicineName: normalizeMedicineName("Augmentin"),             availableQuantity: 45,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Ibuprofen",              normalizedMedicineName: normalizeMedicineName("Ibuprofen"),             availableQuantity: 80,  unit: "strip",   unitPrice: 28  },
      { medicineName: "Ibuprofen 400mg",        normalizedMedicineName: normalizeMedicineName("Ibuprofen 400mg"),       availableQuantity: 80,  unit: "strip",   unitPrice: 28  },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 70,  unit: "strip",   unitPrice: 35  },
      { medicineName: "Cetirizine 10mg",        normalizedMedicineName: normalizeMedicineName("Cetirizine 10mg"),       availableQuantity: 70,  unit: "strip",   unitPrice: 35  },
      { medicineName: "Metformin",              normalizedMedicineName: normalizeMedicineName("Metformin"),             availableQuantity: 90,  unit: "strip",   unitPrice: 42  },
      { medicineName: "Metformin 500mg",        normalizedMedicineName: normalizeMedicineName("Metformin 500mg"),       availableQuantity: 90,  unit: "strip",   unitPrice: 42  },
      { medicineName: "Atorvastatin",           normalizedMedicineName: normalizeMedicineName("Atorvastatin"),          availableQuantity: 60,  unit: "strip",   unitPrice: 110 },
      { medicineName: "Atorvastatin 10mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 10mg"),     availableQuantity: 60,  unit: "strip",   unitPrice: 110 },
      { medicineName: "Atorvastatin 20mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 20mg"),     availableQuantity: 60,  unit: "strip",   unitPrice: 120 },
      { medicineName: "Pan-D",                  normalizedMedicineName: normalizeMedicineName("Pan-D"),                 availableQuantity: 50,  unit: "strip",   unitPrice: 85  },
      { medicineName: "Telma 40",               normalizedMedicineName: normalizeMedicineName("Telma 40"),              availableQuantity: 40,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telma",                  normalizedMedicineName: normalizeMedicineName("Telma"),                 availableQuantity: 40,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telmisartan",            normalizedMedicineName: normalizeMedicineName("Telmisartan"),           availableQuantity: 40,  unit: "strip",   unitPrice: 145 },
      { medicineName: "Telmisartan 40mg",       normalizedMedicineName: normalizeMedicineName("Telmisartan 40mg"),      availableQuantity: 40,  unit: "strip",   unitPrice: 145 },
    ],
  },
  {
    id: "pharm_quickcare",
    name: "QuickCare Pharmacy",
    address: "HAL 2nd Stage, Defence Colony",
    latitude: 12.9654,
    longitude: 77.6492,
    open: true,
    preparationTimeMinutes: 4,
    deliveryTimeMinutes: 8,
    rating: 4.9,
    phone: "+91 80 4789 0123",
    tagline: "Dedicated cold-chain & essential generic dispensary",
    inventory: [
      { medicineName: "ORS",                    normalizedMedicineName: normalizeMedicineName("ORS"),                   availableQuantity: 80,  unit: "sachet",  unitPrice: 22  },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 50,  unit: "strip",   unitPrice: 35  },
      { medicineName: "Dolo 650",               normalizedMedicineName: normalizeMedicineName("Dolo 650"),              availableQuantity: 2,   unit: "strip",   unitPrice: 34  }, // Low stock on purpose
      { medicineName: "Vitamin C 500mg",        normalizedMedicineName: normalizeMedicineName("Vitamin C 500mg"),       availableQuantity: 90,  unit: "strip",   unitPrice: 28  },
      { medicineName: "Amlodipine",             normalizedMedicineName: normalizeMedicineName("Amlodipine"),            availableQuantity: 55,  unit: "strip",   unitPrice: 45  },
      { medicineName: "Amlodipine 5mg",         normalizedMedicineName: normalizeMedicineName("Amlodipine 5mg"),        availableQuantity: 55,  unit: "strip",   unitPrice: 45  },
      { medicineName: "Lisinopril",             normalizedMedicineName: normalizeMedicineName("Lisinopril"),            availableQuantity: 40,  unit: "strip",   unitPrice: 60  },
      { medicineName: "Lisinopril 5mg",         normalizedMedicineName: normalizeMedicineName("Lisinopril 5mg"),        availableQuantity: 40,  unit: "strip",   unitPrice: 60  },
      { medicineName: "Losartan",               normalizedMedicineName: normalizeMedicineName("Losartan"),              availableQuantity: 45,  unit: "strip",   unitPrice: 70  },
      { medicineName: "Losartan 50mg",          normalizedMedicineName: normalizeMedicineName("Losartan 50mg"),         availableQuantity: 45,  unit: "strip",   unitPrice: 70  },
      { medicineName: "Ondansetron",            normalizedMedicineName: normalizeMedicineName("Ondansetron"),           availableQuantity: 35,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Ondansetron 4mg",        normalizedMedicineName: normalizeMedicineName("Ondansetron 4mg"),       availableQuantity: 35,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Domperidone",            normalizedMedicineName: normalizeMedicineName("Domperidone"),           availableQuantity: 60,  unit: "strip",   unitPrice: 48  },
      { medicineName: "Metronidazole",          normalizedMedicineName: normalizeMedicineName("Metronidazole"),         availableQuantity: 50,  unit: "strip",   unitPrice: 30  },
      { medicineName: "Metronidazole 400mg",    normalizedMedicineName: normalizeMedicineName("Metronidazole 400mg"),   availableQuantity: 50,  unit: "strip",   unitPrice: 30  },
    ],
  },
  {
    id: "pharm_lifeline_mega",
    name: "LifeLine Mega Medicals",
    address: "Outer Ring Road Junction, Domlur",
    latitude: 12.9350,
    longitude: 77.6820,
    open: true,
    preparationTimeMinutes: 12,
    deliveryTimeMinutes: 18,
    rating: 4.6,
    phone: "+91 80 4999 8888",
    tagline: "Large central warehouse with comprehensive stock",
    inventory: [
      { medicineName: "Dolo 650",               normalizedMedicineName: normalizeMedicineName("Dolo 650"),              availableQuantity: 300, unit: "strip",   unitPrice: 32  },
      { medicineName: "Pantoprazole",           normalizedMedicineName: normalizeMedicineName("Pantoprazole"),          availableQuantity: 200, unit: "strip",   unitPrice: 78  },
      { medicineName: "Azithromycin",           normalizedMedicineName: normalizeMedicineName("Azithromycin"),          availableQuantity: 150, unit: "strip",   unitPrice: 125 },
      { medicineName: "ORS",                    normalizedMedicineName: normalizeMedicineName("ORS"),                   availableQuantity: 200, unit: "sachet",  unitPrice: 24  },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 120, unit: "strip",   unitPrice: 36  },
      { medicineName: "Amoxicillin",            normalizedMedicineName: normalizeMedicineName("Amoxicillin"),           availableQuantity: 100, unit: "strip",   unitPrice: 90  },
      { medicineName: "Augmentin 625mg",        normalizedMedicineName: normalizeMedicineName("Augmentin 625mg"),       availableQuantity: 80,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Augmentin",              normalizedMedicineName: normalizeMedicineName("Augmentin"),             availableQuantity: 80,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Metformin",              normalizedMedicineName: normalizeMedicineName("Metformin"),             availableQuantity: 150, unit: "strip",   unitPrice: 40  },
      { medicineName: "Metformin 500mg",        normalizedMedicineName: normalizeMedicineName("Metformin 500mg"),       availableQuantity: 150, unit: "strip",   unitPrice: 40  },
      { medicineName: "Atorvastatin",           normalizedMedicineName: normalizeMedicineName("Atorvastatin"),          availableQuantity: 90,  unit: "strip",   unitPrice: 108 },
      { medicineName: "Atorvastatin 10mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 10mg"),     availableQuantity: 90,  unit: "strip",   unitPrice: 108 },
      { medicineName: "Atorvastatin 20mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 20mg"),     availableQuantity: 80,  unit: "strip",   unitPrice: 118 },
      { medicineName: "Telma 40",               normalizedMedicineName: normalizeMedicineName("Telma 40"),              availableQuantity: 70,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telma",                  normalizedMedicineName: normalizeMedicineName("Telma"),                 availableQuantity: 70,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telmisartan",            normalizedMedicineName: normalizeMedicineName("Telmisartan"),           availableQuantity: 70,  unit: "strip",   unitPrice: 145 },
      { medicineName: "Telmisartan 40mg",       normalizedMedicineName: normalizeMedicineName("Telmisartan 40mg"),      availableQuantity: 70,  unit: "strip",   unitPrice: 145 },
      { medicineName: "Pan-D",                  normalizedMedicineName: normalizeMedicineName("Pan-D"),                 availableQuantity: 80,  unit: "strip",   unitPrice: 85  },
      { medicineName: "Omeprazole",             normalizedMedicineName: normalizeMedicineName("Omeprazole"),            availableQuantity: 100, unit: "strip",   unitPrice: 55  },
      { medicineName: "Omeprazole 20mg",        normalizedMedicineName: normalizeMedicineName("Omeprazole 20mg"),       availableQuantity: 100, unit: "strip",   unitPrice: 55  },
      { medicineName: "Ranitidine",             normalizedMedicineName: normalizeMedicineName("Ranitidine"),            availableQuantity: 60,  unit: "strip",   unitPrice: 30  },
      { medicineName: "Clopidogrel",            normalizedMedicineName: normalizeMedicineName("Clopidogrel"),           availableQuantity: 50,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Clopidogrel 75mg",       normalizedMedicineName: normalizeMedicineName("Clopidogrel 75mg"),      availableQuantity: 50,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Aspirin",                normalizedMedicineName: normalizeMedicineName("Aspirin"),               availableQuantity: 80,  unit: "strip",   unitPrice: 25  },
      { medicineName: "Aspirin 75mg",           normalizedMedicineName: normalizeMedicineName("Aspirin 75mg"),          availableQuantity: 80,  unit: "strip",   unitPrice: 25  },
    ],
  },
  {
    id: "pharm_healthfirst",
    name: "HealthFirst Pharmacy",
    address: "Old Airport Road, Kodihalli",
    latitude: 12.9610,
    longitude: 77.6520,
    open: true,
    preparationTimeMinutes: 6,
    deliveryTimeMinutes: 10,
    rating: 4.7,
    phone: "+91 80 4432 1098",
    tagline: "Neighborhood family medical store",
    inventory: [
      { medicineName: "Dolo 650",               normalizedMedicineName: normalizeMedicineName("Dolo 650"),              availableQuantity: 50,  unit: "strip",   unitPrice: 33  },
      { medicineName: "Pantoprazole",           normalizedMedicineName: normalizeMedicineName("Pantoprazole"),          availableQuantity: 40,  unit: "strip",   unitPrice: 76  },
      { medicineName: "Amoxicillin",            normalizedMedicineName: normalizeMedicineName("Amoxicillin"),           availableQuantity: 30,  unit: "strip",   unitPrice: 92  },
      { medicineName: "Augmentin 625mg",        normalizedMedicineName: normalizeMedicineName("Augmentin 625mg"),       availableQuantity: 25,  unit: "strip",   unitPrice: 188 },
      { medicineName: "Augmentin",              normalizedMedicineName: normalizeMedicineName("Augmentin"),             availableQuantity: 25,  unit: "strip",   unitPrice: 188 },
      { medicineName: "Ibuprofen 400mg",        normalizedMedicineName: normalizeMedicineName("Ibuprofen 400mg"),       availableQuantity: 60,  unit: "strip",   unitPrice: 25  },
      { medicineName: "Ibuprofen",              normalizedMedicineName: normalizeMedicineName("Ibuprofen"),             availableQuantity: 60,  unit: "strip",   unitPrice: 25  },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 55,  unit: "strip",   unitPrice: 32  },
      { medicineName: "Cetirizine 10mg",        normalizedMedicineName: normalizeMedicineName("Cetirizine 10mg"),       availableQuantity: 55,  unit: "strip",   unitPrice: 32  },
      { medicineName: "Fexofenadine",           normalizedMedicineName: normalizeMedicineName("Fexofenadine"),          availableQuantity: 30,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Fexofenadine 120mg",     normalizedMedicineName: normalizeMedicineName("Fexofenadine 120mg"),    availableQuantity: 30,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Montair-LC",             normalizedMedicineName: normalizeMedicineName("Montair-LC"),            availableQuantity: 30,  unit: "strip",   unitPrice: 165 },
      { medicineName: "Montelukast",            normalizedMedicineName: normalizeMedicineName("Montelukast"),           availableQuantity: 30,  unit: "strip",   unitPrice: 160 },
      { medicineName: "Levocetirizine",         normalizedMedicineName: normalizeMedicineName("Levocetirizine"),        availableQuantity: 40,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Levocetirizine 5mg",     normalizedMedicineName: normalizeMedicineName("Levocetirizine 5mg"),    availableQuantity: 40,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Metformin",              normalizedMedicineName: normalizeMedicineName("Metformin"),             availableQuantity: 70,  unit: "strip",   unitPrice: 44  },
      { medicineName: "Metformin 500mg",        normalizedMedicineName: normalizeMedicineName("Metformin 500mg"),       availableQuantity: 70,  unit: "strip",   unitPrice: 44  },
      { medicineName: "Glimepiride",            normalizedMedicineName: normalizeMedicineName("Glimepiride"),           availableQuantity: 35,  unit: "strip",   unitPrice: 75  },
      { medicineName: "Glimepiride 1mg",        normalizedMedicineName: normalizeMedicineName("Glimepiride 1mg"),       availableQuantity: 35,  unit: "strip",   unitPrice: 75  },
      { medicineName: "Glimepiride 2mg",        normalizedMedicineName: normalizeMedicineName("Glimepiride 2mg"),       availableQuantity: 25,  unit: "strip",   unitPrice: 95  },
    ],
  },
  {
    id: "pharm_sunrise",
    name: "Sunrise Medical Store",
    address: "Ulsoor Lake Road, Someshwarpura",
    latitude: 12.9840,
    longitude: 77.6210,
    open: true,
    preparationTimeMinutes: 7,
    deliveryTimeMinutes: 12,
    rating: 4.5,
    phone: "+91 80 4876 5432",
    tagline: "Local pharmacy specializing in respiratory and fever aids",
    inventory: [
      { medicineName: "ORS",                    normalizedMedicineName: normalizeMedicineName("ORS"),                   availableQuantity: 80,  unit: "sachet",  unitPrice: 20  },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 60,  unit: "strip",   unitPrice: 32  },
      { medicineName: "Montair-LC",             normalizedMedicineName: normalizeMedicineName("Montair-LC"),            availableQuantity: 30,  unit: "strip",   unitPrice: 165 },
      { medicineName: "Paracetamol 500mg",      normalizedMedicineName: normalizeMedicineName("Paracetamol 500mg"),     availableQuantity: 150, unit: "strip",   unitPrice: 18  },
      { medicineName: "Telma 40",               normalizedMedicineName: normalizeMedicineName("Telma 40"),              availableQuantity: 50,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Telma",                  normalizedMedicineName: normalizeMedicineName("Telma"),                 availableQuantity: 50,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Telmisartan",            normalizedMedicineName: normalizeMedicineName("Telmisartan"),           availableQuantity: 50,  unit: "strip",   unitPrice: 143 },
      { medicineName: "Telmisartan 40mg",       normalizedMedicineName: normalizeMedicineName("Telmisartan 40mg"),      availableQuantity: 50,  unit: "strip",   unitPrice: 143 },
      { medicineName: "Amlodipine",             normalizedMedicineName: normalizeMedicineName("Amlodipine"),            availableQuantity: 50,  unit: "strip",   unitPrice: 48  },
      { medicineName: "Amlodipine 5mg",         normalizedMedicineName: normalizeMedicineName("Amlodipine 5mg"),        availableQuantity: 50,  unit: "strip",   unitPrice: 48  },
      { medicineName: "Pan-D",                  normalizedMedicineName: normalizeMedicineName("Pan-D"),                 availableQuantity: 40,  unit: "strip",   unitPrice: 82  },
      { medicineName: "Rabeprazole",            normalizedMedicineName: normalizeMedicineName("Rabeprazole"),           availableQuantity: 45,  unit: "strip",   unitPrice: 90  },
      { medicineName: "Ranitidine",             normalizedMedicineName: normalizeMedicineName("Ranitidine"),            availableQuantity: 50,  unit: "strip",   unitPrice: 28  },
      { medicineName: "Azithromycin",           normalizedMedicineName: normalizeMedicineName("Azithromycin"),          availableQuantity: 30,  unit: "strip",   unitPrice: 118 },
      { medicineName: "Clindamycin",            normalizedMedicineName: normalizeMedicineName("Clindamycin"),           availableQuantity: 20,  unit: "strip",   unitPrice: 145 },
      { medicineName: "Clindamycin 300mg",      normalizedMedicineName: normalizeMedicineName("Clindamycin 300mg"),     availableQuantity: 20,  unit: "strip",   unitPrice: 145 },
    ],
  },
  {
    id: "pharm_metrohealth",
    name: "MetroHealth Dispensary",
    address: "Cunningham Road, Vasanth Nagar",
    latitude: 12.9910,
    longitude: 77.5950,
    open: true,
    preparationTimeMinutes: 10,
    deliveryTimeMinutes: 15,
    rating: 4.7,
    phone: "+91 80 4555 1234",
    tagline: "Trauma and chronic disease prescription center",
    inventory: [
      { medicineName: "Azithromycin",           normalizedMedicineName: normalizeMedicineName("Azithromycin"),          availableQuantity: 60,  unit: "strip",   unitPrice: 122 },
      { medicineName: "Amoxicillin",            normalizedMedicineName: normalizeMedicineName("Amoxicillin"),           availableQuantity: 60,  unit: "strip",   unitPrice: 90  },
      { medicineName: "Augmentin 625mg",        normalizedMedicineName: normalizeMedicineName("Augmentin 625mg"),       availableQuantity: 55,  unit: "strip",   unitPrice: 190 },
      { medicineName: "Augmentin",              normalizedMedicineName: normalizeMedicineName("Augmentin"),             availableQuantity: 55,  unit: "strip",   unitPrice: 190 },
      { medicineName: "Metformin",              normalizedMedicineName: normalizeMedicineName("Metformin"),             availableQuantity: 120, unit: "strip",   unitPrice: 42  },
      { medicineName: "Metformin 500mg",        normalizedMedicineName: normalizeMedicineName("Metformin 500mg"),       availableQuantity: 120, unit: "strip",   unitPrice: 42  },
      { medicineName: "Metformin 1000mg",       normalizedMedicineName: normalizeMedicineName("Metformin 1000mg"),      availableQuantity: 60,  unit: "strip",   unitPrice: 75  },
      { medicineName: "Salbutamol Inhaler",     normalizedMedicineName: normalizeMedicineName("Salbutamol Inhaler"),    availableQuantity: 20,  unit: "inhaler", unitPrice: 145 },
      { medicineName: "Salbutamol",             normalizedMedicineName: normalizeMedicineName("Salbutamol"),            availableQuantity: 20,  unit: "inhaler", unitPrice: 145 },
      { medicineName: "Insulin Glargine",       normalizedMedicineName: normalizeMedicineName("Insulin Glargine"),      availableQuantity: 15,  unit: "vial",    unitPrice: 650 },
      { medicineName: "Insulin",               normalizedMedicineName: normalizeMedicineName("Insulin"),               availableQuantity: 15,  unit: "vial",    unitPrice: 650 },
      { medicineName: "Enoxaparin",             normalizedMedicineName: normalizeMedicineName("Enoxaparin"),            availableQuantity: 20,  unit: "injection", unitPrice: 480 },
      { medicineName: "Atorvastatin",           normalizedMedicineName: normalizeMedicineName("Atorvastatin"),          availableQuantity: 80,  unit: "strip",   unitPrice: 105 },
      { medicineName: "Atorvastatin 20mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 20mg"),     availableQuantity: 80,  unit: "strip",   unitPrice: 115 },
      { medicineName: "Rosuvastatin",           normalizedMedicineName: normalizeMedicineName("Rosuvastatin"),          availableQuantity: 50,  unit: "strip",   unitPrice: 135 },
      { medicineName: "Rosuvastatin 10mg",      normalizedMedicineName: normalizeMedicineName("Rosuvastatin 10mg"),     availableQuantity: 50,  unit: "strip",   unitPrice: 135 },
      { medicineName: "Telmisartan",            normalizedMedicineName: normalizeMedicineName("Telmisartan"),           availableQuantity: 55,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Telmisartan 40mg",       normalizedMedicineName: normalizeMedicineName("Telmisartan 40mg"),      availableQuantity: 55,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Losartan",               normalizedMedicineName: normalizeMedicineName("Losartan"),              availableQuantity: 45,  unit: "strip",   unitPrice: 72  },
      { medicineName: "Losartan 50mg",          normalizedMedicineName: normalizeMedicineName("Losartan 50mg"),         availableQuantity: 45,  unit: "strip",   unitPrice: 72  },
      { medicineName: "Aspirin",                normalizedMedicineName: normalizeMedicineName("Aspirin"),               availableQuantity: 90,  unit: "strip",   unitPrice: 22  },
      { medicineName: "Aspirin 75mg",           normalizedMedicineName: normalizeMedicineName("Aspirin 75mg"),          availableQuantity: 90,  unit: "strip",   unitPrice: 22  },
      { medicineName: "Clopidogrel",            normalizedMedicineName: normalizeMedicineName("Clopidogrel"),           availableQuantity: 60,  unit: "strip",   unitPrice: 92  },
      { medicineName: "Clopidogrel 75mg",       normalizedMedicineName: normalizeMedicineName("Clopidogrel 75mg"),      availableQuantity: 60,  unit: "strip",   unitPrice: 92  },
      { medicineName: "Ramipril",               normalizedMedicineName: normalizeMedicineName("Ramipril"),              availableQuantity: 40,  unit: "strip",   unitPrice: 68  },
      { medicineName: "Ramipril 5mg",           normalizedMedicineName: normalizeMedicineName("Ramipril 5mg"),          availableQuantity: 40,  unit: "strip",   unitPrice: 68  },
    ],
  },
  {
    id: "pharm_apollo_express",
    name: "Apollo Pharmacy Express",
    address: "MG Road Junction, Brigade Road",
    latitude: 12.9758,
    longitude: 77.6095,
    open: true,
    preparationTimeMinutes: 5,
    deliveryTimeMinutes: 9,
    rating: 4.8,
    phone: "+91 98450 12345",
    tagline: "Apollo chain — premium stock with same-day delivery SLA",
    inventory: [
      { medicineName: "Dolo 650",               normalizedMedicineName: normalizeMedicineName("Dolo 650"),              availableQuantity: 200, unit: "strip",   unitPrice: 32  },
      { medicineName: "Pantoprazole",           normalizedMedicineName: normalizeMedicineName("Pantoprazole"),          availableQuantity: 100, unit: "strip",   unitPrice: 75  },
      { medicineName: "Pan-D",                  normalizedMedicineName: normalizeMedicineName("Pan-D"),                 availableQuantity: 90,  unit: "strip",   unitPrice: 85  },
      { medicineName: "Azithromycin",           normalizedMedicineName: normalizeMedicineName("Azithromycin"),          availableQuantity: 80,  unit: "strip",   unitPrice: 118 },
      { medicineName: "Augmentin",              normalizedMedicineName: normalizeMedicineName("Augmentin"),             availableQuantity: 70,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Augmentin 625mg",        normalizedMedicineName: normalizeMedicineName("Augmentin 625mg"),       availableQuantity: 70,  unit: "strip",   unitPrice: 185 },
      { medicineName: "Telma 40",               normalizedMedicineName: normalizeMedicineName("Telma 40"),              availableQuantity: 80,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telma",                  normalizedMedicineName: normalizeMedicineName("Telma"),                 availableQuantity: 80,  unit: "strip",   unitPrice: 150 },
      { medicineName: "Telmisartan",            normalizedMedicineName: normalizeMedicineName("Telmisartan"),           availableQuantity: 80,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Telmisartan 40mg",       normalizedMedicineName: normalizeMedicineName("Telmisartan 40mg"),      availableQuantity: 80,  unit: "strip",   unitPrice: 148 },
      { medicineName: "Metformin",              normalizedMedicineName: normalizeMedicineName("Metformin"),             availableQuantity: 100, unit: "strip",   unitPrice: 42  },
      { medicineName: "Metformin 500mg",        normalizedMedicineName: normalizeMedicineName("Metformin 500mg"),       availableQuantity: 100, unit: "strip",   unitPrice: 42  },
      { medicineName: "Glimepiride",            normalizedMedicineName: normalizeMedicineName("Glimepiride"),           availableQuantity: 60,  unit: "strip",   unitPrice: 78  },
      { medicineName: "Glimepiride 2mg",        normalizedMedicineName: normalizeMedicineName("Glimepiride 2mg"),       availableQuantity: 60,  unit: "strip",   unitPrice: 95  },
      { medicineName: "Atorvastatin",           normalizedMedicineName: normalizeMedicineName("Atorvastatin"),          availableQuantity: 80,  unit: "strip",   unitPrice: 108 },
      { medicineName: "Atorvastatin 10mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 10mg"),     availableQuantity: 80,  unit: "strip",   unitPrice: 108 },
      { medicineName: "Atorvastatin 20mg",      normalizedMedicineName: normalizeMedicineName("Atorvastatin 20mg"),     availableQuantity: 70,  unit: "strip",   unitPrice: 118 },
      { medicineName: "Rosuvastatin",           normalizedMedicineName: normalizeMedicineName("Rosuvastatin"),          availableQuantity: 50,  unit: "strip",   unitPrice: 132 },
      { medicineName: "Cetirizine",             normalizedMedicineName: normalizeMedicineName("Cetirizine"),            availableQuantity: 80,  unit: "strip",   unitPrice: 35  },
      { medicineName: "Cetirizine 10mg",        normalizedMedicineName: normalizeMedicineName("Cetirizine 10mg"),       availableQuantity: 80,  unit: "strip",   unitPrice: 35  },
      { medicineName: "ORS",                    normalizedMedicineName: normalizeMedicineName("ORS"),                   availableQuantity: 100, unit: "sachet",  unitPrice: 22  },
      { medicineName: "Ibuprofen",              normalizedMedicineName: normalizeMedicineName("Ibuprofen"),             availableQuantity: 80,  unit: "strip",   unitPrice: 27  },
      { medicineName: "Ibuprofen 400mg",        normalizedMedicineName: normalizeMedicineName("Ibuprofen 400mg"),       availableQuantity: 80,  unit: "strip",   unitPrice: 27  },
      { medicineName: "Amlodipine",             normalizedMedicineName: normalizeMedicineName("Amlodipine"),            availableQuantity: 60,  unit: "strip",   unitPrice: 46  },
      { medicineName: "Amlodipine 5mg",         normalizedMedicineName: normalizeMedicineName("Amlodipine 5mg"),        availableQuantity: 60,  unit: "strip",   unitPrice: 46  },
      { medicineName: "Losartan",               normalizedMedicineName: normalizeMedicineName("Losartan"),              availableQuantity: 50,  unit: "strip",   unitPrice: 70  },
      { medicineName: "Losartan 50mg",          normalizedMedicineName: normalizeMedicineName("Losartan 50mg"),         availableQuantity: 50,  unit: "strip",   unitPrice: 70  },
      { medicineName: "Ramipril",               normalizedMedicineName: normalizeMedicineName("Ramipril"),              availableQuantity: 45,  unit: "strip",   unitPrice: 65  },
      { medicineName: "Levothyroxine",          normalizedMedicineName: normalizeMedicineName("Levothyroxine"),         availableQuantity: 40,  unit: "strip",   unitPrice: 72  },
      { medicineName: "Levothyroxine 50mcg",    normalizedMedicineName: normalizeMedicineName("Levothyroxine 50mcg"),   availableQuantity: 40,  unit: "strip",   unitPrice: 72  },
      { medicineName: "Metronidazole",          normalizedMedicineName: normalizeMedicineName("Metronidazole"),         availableQuantity: 55,  unit: "strip",   unitPrice: 30  },
      { medicineName: "Metronidazole 400mg",    normalizedMedicineName: normalizeMedicineName("Metronidazole 400mg"),   availableQuantity: 55,  unit: "strip",   unitPrice: 30  },
      { medicineName: "Ondansetron",            normalizedMedicineName: normalizeMedicineName("Ondansetron"),           availableQuantity: 45,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Ondansetron 4mg",        normalizedMedicineName: normalizeMedicineName("Ondansetron 4mg"),       availableQuantity: 45,  unit: "strip",   unitPrice: 55  },
      { medicineName: "Domperidone",            normalizedMedicineName: normalizeMedicineName("Domperidone"),           availableQuantity: 60,  unit: "strip",   unitPrice: 48  },
      { medicineName: "Vitamin C 500mg",        normalizedMedicineName: normalizeMedicineName("Vitamin C 500mg"),       availableQuantity: 90,  unit: "strip",   unitPrice: 28  },
      { medicineName: "Vitamin D3",             normalizedMedicineName: normalizeMedicineName("Vitamin D3"),            availableQuantity: 70,  unit: "strip",   unitPrice: 85  },
      { medicineName: "Calcium Carbonate",      normalizedMedicineName: normalizeMedicineName("Calcium Carbonate"),     availableQuantity: 60,  unit: "strip",   unitPrice: 65  },
      { medicineName: "Aspirin",                normalizedMedicineName: normalizeMedicineName("Aspirin"),               availableQuantity: 90,  unit: "strip",   unitPrice: 24  },
      { medicineName: "Aspirin 75mg",           normalizedMedicineName: normalizeMedicineName("Aspirin 75mg"),          availableQuantity: 90,  unit: "strip",   unitPrice: 24  },
      { medicineName: "Clopidogrel",            normalizedMedicineName: normalizeMedicineName("Clopidogrel"),           availableQuantity: 55,  unit: "strip",   unitPrice: 90  },
      { medicineName: "Clopidogrel 75mg",       normalizedMedicineName: normalizeMedicineName("Clopidogrel 75mg"),      availableQuantity: 55,  unit: "strip",   unitPrice: 90  },
    ],
  },
];

export class DemoPharmacyProvider implements PharmacyDataProvider {
  private pharmacies: Pharmacy[];

  constructor(customData?: Pharmacy[]) {
    this.pharmacies = customData ? [...customData] : [...DEMO_PHARMACIES_DATA];
  }

  async getPharmacies(): Promise<Pharmacy[]> {
    return JSON.parse(JSON.stringify(this.pharmacies));
  }

  async getPharmacyById(id: string): Promise<Pharmacy | null> {
    const found = this.pharmacies.find(p => p.id === id);
    return found ? JSON.parse(JSON.stringify(found)) : null;
  }
}

export const demoPharmacyProvider = new DemoPharmacyProvider();
